-- Migration: Fix profiles table FK constraint for pending users approval workflow
-- Feature: 002-user-registration-approval
-- Date: 2025-11-08
-- Purpose: Resolve FK constraint violation when approving pending users
--
-- Root Cause Analysis:
-- - pending_users.id: Generated by app (UUID v4)
-- - profiles.id: Previously had FK → auth.users.id (Supabase Auth)
-- - When approving, code tries to INSERT into profiles with pending_user.id
-- - This violates FK constraint because pending_user.id ≠ auth.users.id
--
-- Solution:
-- - Remove FK constraint from profiles.id
-- - profiles.id becomes independent UUID (matches pending_user.id on approval)
-- - Add unique constraint on email for user lookups
-- - Approve workflow: pending_user.id → profiles.id directly

-- BEGIN MIGRATION

-- Step 1: Drop the problematic FK constraint if it exists
ALTER TABLE profiles
DROP CONSTRAINT IF EXISTS profiles_id_fkey;

-- Step 2: Ensure profiles has unique constraint on email for lookups
-- First drop if exists (constraint add doesn't support IF NOT EXISTS)
ALTER TABLE profiles
DROP CONSTRAINT IF EXISTS uq_profiles_email;

ALTER TABLE profiles
ADD CONSTRAINT uq_profiles_email UNIQUE (email);

-- Step 3: Add index on email for fast lookups
CREATE INDEX IF NOT EXISTS idx_profiles_email
ON profiles(email);

-- Document the schema change
COMMENT ON TABLE profiles IS 'Active user profiles. ID matches pending_users.id upon approval. Not FK-constrained to auth.users anymore.';
COMMENT ON COLUMN profiles.id IS 'UUID from pending_users when user was approved. No FK constraint to allow workflow flexibility.';
COMMENT ON COLUMN profiles.email IS 'Unique email address for user lookups and authentication.';

-- END MIGRATION

-- BEGIN ROLLBACK

-- Restore FK constraint (original was FK to auth.users.id)
-- Note: This will fail if profiles contain IDs that don't exist in auth.users
-- ALTER TABLE profiles
-- ADD CONSTRAINT profiles_id_fkey
-- FOREIGN KEY (id) REFERENCES auth.users(id);

-- Drop unique constraint
ALTER TABLE profiles
DROP CONSTRAINT IF EXISTS uq_profiles_email;

-- Drop index
DROP INDEX IF EXISTS idx_profiles_email;

-- END ROLLBACK
