/**
 * Ticket System API Functions
 * Client-side functions for interacting with the ticketing system via Golang backend
 */

import { supabase } from '@/lib/conn/supabaseClient';
import {
  TicketStatus,
  type EnhancedSilpanaData,
  type TicketLookupRequest,
  type TicketLookupResponse,
  type TicketStatusUpdate,
  type TicketHistory,
  type TicketCommunication,
  type CommunicationMessage
} from '@/types/silpana/silpana';
import * as golangApi from '@/lib/api/golang-backend';

// Check if we should use Golang backend
const USE_GOLANG_BACKEND = process.env.NEXT_PUBLIC_ENABLE_GO_BACKEND === 'true' || 
                           process.env.NEXT_PUBLIC_BACKEND_URL !== undefined;

/**
 * Submit a new ticket (enhanced silpana form submission)
 */
export async function submitTicket(ticketData: Partial<EnhancedSilpanaData>): Promise<{
  success: boolean;
  ticket?: EnhancedSilpanaData;
  ticketCode?: string;
  error?: string;
}> {
  // Use Golang backend if enabled
  if (USE_GOLANG_BACKEND) {
    return await golangApi.submitTicket(ticketData);
  }

  // Fallback to Supabase direct access
  try {
    // Get client IP address for audit trail
    const clientIP = await getClientIP();
    
    const dataToSubmit = {
      ...ticketData,
      created_by_ip: clientIP,
      // ticket_code will be auto-generated by database trigger
      // ticket_status will default to 'submitted'
      // priority_level will default to 'medium' unless specified
    };

    const { data, error } = await supabase
      .from('silpana')
      .insert([dataToSubmit])
      .select('*')
      .single();

    if (error) {
      console.error('Error submitting ticket:', error);
      return {
        success: false,
        error: `Gagal menyimpan pengaduan: ${error.message}`
      };
    }

    return {
      success: true,
      ticket: data as EnhancedSilpanaData,
      ticketCode: data.ticket_code
    };
  } catch (error: any) {
    console.error('Error in submitTicket:', error);
    return {
      success: false,
      error: 'Terjadi kesalahan saat menyimpan pengaduan'
    };
  }
}

/**
 * Look up a ticket by ticket code with verification
 */
export async function lookupTicket(request: TicketLookupRequest): Promise<TicketLookupResponse> {
  // Use Golang backend if enabled
  if (USE_GOLANG_BACKEND) {
    const verificationType = request.phone_number ? 'phone' : 'nik';
    const verificationValue = request.phone_number || request.nik || '';
    
    const result = await golangApi.lookupTicket(
      request.ticket_code,
      verificationType,
      verificationValue
    );

    return {
      ticket: result.ticket || null,
      error: result.error,
      verified: result.success
    };
  }

  // Fallback to Supabase direct access
  try {
    if (!request.ticket_code) {
      return {
        ticket: null,
        error: 'Kode tiket harus diisi',
        verified: false
      };
    }

    // Build verification query
    let query = supabase
      .from('silpana')
      .select('*')
      .eq('ticket_code', request.ticket_code.toUpperCase());

    // Add verification criteria
    if (request.phone_number) {
      query = query.eq('nomor_telepon', request.phone_number);
    } else if (request.nik) {
      query = query.eq('nik_pengaduan', request.nik);
    } else {
      return {
        ticket: null,
        error: 'Nomor telepon atau NIK harus diisi untuk verifikasi',
        verified: false
      };
    }

    const { data, error } = await query.single();

    if (error) {
      if (error.code === 'PGRST116') {
        return {
          ticket: null,
          error: 'Tiket tidak ditemukan atau data verifikasi tidak sesuai',
          verified: false
        };
      }
      
      console.error('Error looking up ticket:', error);
      return {
        ticket: null,
        error: 'Terjadi kesalahan saat mencari tiket',
        verified: false
      };
    }

    // Fetch ticket history and communications
    const ticketWithDetails = await enrichTicketData(data as EnhancedSilpanaData);

    return {
      ticket: ticketWithDetails,
      verified: true
    };
  } catch (error: any) {
    console.error('Error in lookupTicket:', error);
    return {
      ticket: null,
      error: 'Terjadi kesalahan saat mencari tiket',
      verified: false
    };
  }
}

/**
 * Get ticket history
 */
export async function getTicketHistory(ticketId: string): Promise<TicketHistory[]> {
  try {
    const { data, error } = await supabase
      .from('ticket_history')
      .select('*')
      .eq('ticket_id', ticketId)
      .eq('is_public', true)
      .order('changed_at', { ascending: true });

    if (error) {
      console.error('Error fetching ticket history:', error);
      return [];
    }

    return data as TicketHistory[];
  } catch (error) {
    console.error('Error in getTicketHistory:', error);
    return [];
  }
}

/**
 * Get ticket communications
 */
export async function getTicketCommunications(ticketId: string): Promise<TicketCommunication[]> {
  try {
    const { data, error } = await supabase
      .from('ticket_communication')
      .select('*')
      .eq('ticket_id', ticketId)
      .eq('is_internal', false)
      .order('created_at', { ascending: true });

    if (error) {
      console.error('Error fetching ticket communications:', error);
      return [];
    }

    return data as TicketCommunication[];
  } catch (error) {
    console.error('Error in getTicketCommunications:', error);
    return [];
  }
}

/**
 * Add communication to a ticket
 */
export async function addTicketCommunication(message: CommunicationMessage): Promise<{
  success: boolean;
  communication?: TicketCommunication;
  error?: string;
}> {
  try {
    const { data, error } = await supabase
      .from('ticket_communication')
      .insert([{
        ticket_id: message.ticket_id,
        message: message.message,
        sender_type: message.sender_type,
        sender_name: message.sender_name,
        attachments: message.attachments?.map(f => f.name) || [],
        is_internal: message.is_internal || false
      }])
      .select('*')
      .single();

    if (error) {
      console.error('Error adding communication:', error);
      return {
        success: false,
        error: 'Gagal menambahkan komunikasi'
      };
    }

    return {
      success: true,
      communication: data as TicketCommunication
    };
  } catch (error) {
    console.error('Error in addTicketCommunication:', error);
    return {
      success: false,
      error: 'Terjadi kesalahan saat menambahkan komunikasi'
    };
  }
}

/**
 * Update ticket status (admin only)
 */
export async function updateTicketStatus(update: TicketStatusUpdate): Promise<{
  success: boolean;
  ticket?: EnhancedSilpanaData;
  error?: string;
}> {
  try {
    const updateData: any = {
      ticket_status: update.new_status,
      last_updated: new Date().toISOString()
    };

    if (update.estimated_resolution) {
      updateData.estimated_resolution = update.estimated_resolution.toISOString();
    }

    if (update.assigned_to) {
      updateData.assigned_to = update.assigned_to;
    }

    if (update.new_status === TicketStatus.RESOLVED && !updateData.actual_resolution) {
      updateData.actual_resolution = new Date().toISOString();
    }

    const { data, error } = await supabase
      .from('silpana')
      .update(updateData)
      .eq('id', update.ticket_id)
      .select('*')
      .single();

    if (error) {
      console.error('Error updating ticket status:', error);
      return {
        success: false,
        error: 'Gagal mengupdate status tiket'
      };
    }

    // Add history entry if notes provided
    if (update.notes) {
      await supabase
        .from('ticket_history')
        .insert([{
          ticket_id: update.ticket_id,
          status_to: update.new_status,
          changed_by: 'admin', // Should be actual user
          notes: update.notes,
          is_public: true
        }]);
    }

    return {
      success: true,
      ticket: data as EnhancedSilpanaData
    };
  } catch (error) {
    console.error('Error in updateTicketStatus:', error);
    return {
      success: false,
      error: 'Terjadi kesalahan saat mengupdate status'
    };
  }
}

/**
 * Subscribe to real-time ticket updates
 */
export function subscribeToTicketUpdates(
  ticketId: string,
  onUpdate: (ticket: EnhancedSilpanaData) => void
) {
  const subscription = supabase
    .channel('ticket-updates')
    .on('postgres_changes', {
      event: 'UPDATE',
      schema: 'public',
      table: 'silpana',
      filter: `id=eq.${ticketId}`
    }, async (payload) => {
      const updatedTicket = await enrichTicketData(payload.new as EnhancedSilpanaData);
      onUpdate(updatedTicket);
    })
    .subscribe();

  return () => subscription.unsubscribe();
}

/**
 * Subscribe to real-time communication updates
 */
export function subscribeToTicketCommunications(
  ticketId: string,
  onNewCommunication: (communication: TicketCommunication) => void
) {
  const subscription = supabase
    .channel('communication-updates')
    .on('postgres_changes', {
      event: 'INSERT',
      schema: 'public',
      table: 'ticket_communication',
      filter: `ticket_id=eq.${ticketId}`
    }, (payload) => {
      const communication = payload.new as TicketCommunication;
      if (!communication.is_internal) {
        onNewCommunication(communication);
      }
    })
    .subscribe();

  return () => subscription.unsubscribe();
}

/**
 * Enrich ticket data with history and communications
 */
async function enrichTicketData(ticket: EnhancedSilpanaData): Promise<EnhancedSilpanaData> {
  if (!ticket.id) return ticket;

  const [history, communications] = await Promise.all([
    getTicketHistory(ticket.id),
    getTicketCommunications(ticket.id)
  ]);

  return {
    ...ticket,
    ticket_history: history,
    ticket_communications: communications
  };
}

/**
 * Get client IP address for audit trail
 */
async function getClientIP(): Promise<string> {
  try {
    const response = await fetch('https://api.ipify.org?format=json');
    const data = await response.json();
    return data.ip || 'unknown';
  } catch (error) {
    console.warn('Could not get client IP:', error);
    return 'unknown';
  }
}

/**
 * Search tickets with filters
 */
export async function searchTickets(filters: {
  query?: string;
  status?: TicketStatus[];
  priority?: string[];
  dateFrom?: Date;
  dateTo?: Date;
  limit?: number;
  offset?: number;
}): Promise<{
  tickets: EnhancedSilpanaData[];
  totalCount: number;
  error?: string;
}> {
  try {
    let query = supabase
      .from('silpana')
      .select('*', { count: 'exact' })
      .order('created_at', { ascending: false });

    // Apply filters
    if (filters.query) {
      query = query.or(
        `ticket_code.ilike.%${filters.query}%,nama_pengaduan.ilike.%${filters.query}%,alasan_pengaduan.ilike.%${filters.query}%`
      );
    }

    if (filters.status && filters.status.length > 0) {
      query = query.in('ticket_status', filters.status);
    }

    if (filters.priority && filters.priority.length > 0) {
      query = query.in('priority_level', filters.priority);
    }

    if (filters.dateFrom) {
      query = query.gte('created_at', filters.dateFrom.toISOString());
    }

    if (filters.dateTo) {
      query = query.lte('created_at', filters.dateTo.toISOString());
    }

    // Apply pagination
    if (filters.limit && filters.offset !== undefined) {
      query = query.range(filters.offset, filters.offset + filters.limit - 1);
    }

    const { data, error, count } = await query;

    if (error) {
      console.error('Error searching tickets:', error);
      return {
        tickets: [],
        totalCount: 0,
        error: 'Gagal mencari tiket'
      };
    }

    return {
      tickets: data as EnhancedSilpanaData[],
      totalCount: count || 0
    };
  } catch (error) {
    console.error('Error in searchTickets:', error);
    return {
      tickets: [],
      totalCount: 0,
      error: 'Terjadi kesalahan saat mencari tiket'
    };
  }
}